version: '3.3'
services:
  api:
    container_name: api
    restart: always
    build: ./API
    links:
      - mongo
    networks:
      - project
    ports:
      - '5000:5000'
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongodbdata:/data/db
    networks:
      - project
  stream:
    container_name: stream
    restart: always
    build: ./StreamTwitter
    networks:
      - project
  webiste:
    container_name: webiste
    restart: always
    build: ./dashboard
    ports:
      - '3000:3000'
    networks:
      - project

networks: 
  project:
    driver: bridge

volumes:
  mongodbdata:
    driver: local
 