version: '3'
services:
  api:
    container_name: api
    restart: always
    build: ./API
    ports:
      - '5000:5000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongodbdata:/data/db
    ports:
      - '27017:27017'
  stream:
    container_name: stream
    restart: always
    build: ./StreamTwitter
    network_mode: host
  webiste:
    container_name: webiste
    restart: always
    build: ./dashboard
    network_mode: host
volumes:
  mongodbdata:
    driver: local
 